// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";
import { group } from "k6";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    appUrl: "localhost:3000",
    tokenAdmin:
      "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjI1NTU3ODY2fQ.Id3o6HdKlbCZKAtL-NoNT8hpUVKQ3R2gPT_QIZWT928",
    tokenUser:
      "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGFsaGFFamF6QGdtYWlsLmNvbSIsImlhdCI6MTYyNTU1Nzk5MH0.j6FAxSomWRBzB5vvJCk2WYO_V3v9cMgAS6kI72lnCwk",
    email: "talhaEjaz@gmail.com",
    password: "talha123",
   
  },
  environment: {
    BASE_URL: "localhost:3000/api"
  }
});

export default function() {
  group("User", function() {
    postman[Request]({
      name: "Login",
      id: "3e79799b-977b-4c39-aa47-fe58485c04f8",
      method: "GET",
      address: "{{BASE_URL}}/users/login",
      data:
        '{\r\n    "email":"admin@gmail.com",\r\n    "password":"admin123"\r\n}',
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "Signup",
      id: "e6b5b0d0-2c6a-435a-9549-6f7f6902bb22",
      method: "POST",
      address: "{{BASE_URL}}/users/signup",
      data:
        '{\r\n    "email":"talhaEjaz@gmail.com",\r\n    "password":"talha123",\r\n    "name":"talhaB"\r\n}',
      headers: {
        Authorization: "Token "
      },
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "ShowAllUsers",
      id: "6d25413e-e9da-4029-b990-5ee77777d357",
      method: "GET",
      address: "{{BASE_URL}}/users/showAll",
      headers: {
        Authorization:
          "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjI0OTcxNzE3fQ.W0R11y_z0xooAdESvQiZG0-pg1hrm_OaBRltHvwMvoA"
      },
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "deleteUser",
      id: "2f959256-008b-4cd6-8cdd-63d414a065a8",
      method: "DELETE",
      address: "{{BASE_URL}}/users/delete/talhaEjaz@gmail.com",
      headers: {
        Authorization:
          "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjI1MTIyNzc5fQ.S9jXZesrm7PrIN60uCdcmiDl2RAnaU6UCAkKBSHFSMg"
      },
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "updateUser",
      id: "28f09c3f-3551-4a71-96b9-d5e7bbcec19a",
      method: "PUT",
      address: "{{BASE_URL}}/users/update",
      data:
        '{\r\n    "newName":"umar qayyum",\r\n    "oldPassword":"pak123",\r\n    "newPassword":"pak1234"\r\n}',
      headers: {
        Authorization:
          "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGFsaGFAZ21haWwuY29tIiwiaWF0IjoxNjI1MTQ4MzgwfQ.ChQq38YtDvqHZpg7THyqX18uWLXVLj--uTJd2uwd0WI"
      },
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });
  });

  group("Floor", function() {
    postman[Request]({
      name: "addFloor",
      id: "957d5963-f95a-4412-bfde-0f5dc2f6d1bc",
      method: "POST",
      address: "{{BASE_URL}}/floors/addFloor",
      data: '{\r\n    "floorNumber":"22"\r\n}',
      headers: {
        Authorization:
          "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjI1MTIyNzc5fQ.S9jXZesrm7PrIN60uCdcmiDl2RAnaU6UCAkKBSHFSMg"
      },
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "deleteFloor",
      id: "653ebac6-32b9-4934-a16c-2a2ca80640c2",
      method: "DELETE",
      address: "{{BASE_URL}}/floors/removeFloor/22",
      headers: {
        Authorization:
          "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjI1MTIyNzc5fQ.S9jXZesrm7PrIN60uCdcmiDl2RAnaU6UCAkKBSHFSMg"
      },
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "showAllFloors",
      id: "a660c220-75b6-40c1-bf62-546ab0fdb390",
      method: "GET",
      address: "{{BASE_URL}}/floors/showAll",
      headers: {
        Authorization:
          "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjI1MTIyNzc5fQ.S9jXZesrm7PrIN60uCdcmiDl2RAnaU6UCAkKBSHFSMg"
      },
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "checkAvailableSpots",
      id: "cfa75927-33c5-4a98-9b68-221fce3b69c6",
      method: "GET",
      address: "{{BASE_URL}}/floors/checkAvailableSpots/21",
      headers: {
        Authorization:
          "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjI1MTIyNzc5fQ.S9jXZesrm7PrIN60uCdcmiDl2RAnaU6UCAkKBSHFSMg"
      },
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "checkAllAvailableSpots",
      id: "91a931f4-6d70-48e2-8e14-1c8e57346edc",
      method: "GET",
      address: "{{BASE_URL}}/floors/checkAllAvailableSpots",
      headers: {
        Authorization:
          "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjI1MTIyNzc5fQ.S9jXZesrm7PrIN60uCdcmiDl2RAnaU6UCAkKBSHFSMg"
      },
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });
  });

  group("Vehicle", function() {
    postman[Request]({
      name: "addVehicle",
      id: "62ef3b47-faac-413b-b737-e1dec30c9706",
      method: "POST",
      address: "{{BASE_URL}}/vehicles/addVehicle",
      data:
        '{\r\n    "owner":"hashir123@gmail.com",\r\n    "vehicleNumber":"LEW 7806"\r\n}',
      headers: {
        Authorization:
          "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjI1MTIyNzc5fQ.S9jXZesrm7PrIN60uCdcmiDl2RAnaU6UCAkKBSHFSMg"
      },
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "deleteVehicle",
      id: "5b809446-cdc5-40fc-ac49-ca1caf6d372b",
      method: "DELETE",
      address: "{{BASE_URL}}/vehicles/removeVehicle/LEW 7806",
      data: "{\r\n    \r\n}",
      headers: {
        Authorization:
          "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjI1MTIyNzc5fQ.S9jXZesrm7PrIN60uCdcmiDl2RAnaU6UCAkKBSHFSMg"
      },
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "showAllVehicles",
      id: "4314ec12-58e7-4f92-bd2b-3c503ebdb4bd",
      method: "GET",
      address: "{{BASE_URL}}/vehicles/showAll",
      headers: {
        Authorization:
          "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjI1MTIyNzc5fQ.S9jXZesrm7PrIN60uCdcmiDl2RAnaU6UCAkKBSHFSMg"
      },
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "updateVehicle",
      id: "1af01e6f-9919-406e-86a8-8c0e981112d8",
      method: "PUT",
      address: "{{BASE_URL}}/vehicles/updateVehicle",
      data:
        '{\r\n   "newOwner":"hashir@gmail.com",\r\n    "vehicleNumber":"LEW 7805"\r\n}',
      headers: {
        Authorization:
          "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjI1MTIyNzc5fQ.S9jXZesrm7PrIN60uCdcmiDl2RAnaU6UCAkKBSHFSMg"
      },
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "showVehicle",
      id: "dcc5f645-6d1b-485a-881f-2afc2e1fef5c",
      method: "GET",
      address: "{{BASE_URL}}/vehicles/showVehicle/LEW 7805",
      headers: {
        Authorization:
          "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjI1MTIyNzc5fQ.S9jXZesrm7PrIN60uCdcmiDl2RAnaU6UCAkKBSHFSMg"
      },
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });
  });

  group("Booking", function() {
    postman[Request]({
      name: "addBooking",
      id: "4f3a0ab5-e2dd-41e1-a50e-f5e80b8acea6",
      method: "POST",
      address: "{{BASE_URL}}/bookings/addBooking",
      data:
        '{\r\n    "customer":"hashir123@gmail.com",\r\n    "vehicle":"quia voluptas vitae sapiente voluptatem voluptates quisquam",\r\n    "bookingTime":"2021-07-02T12:30:00",\r\n    "bookingDuration":14,\r\n    "floor":21,\r\n    "spotNo":15\r\n}',
      headers: {
        Authorization:
          "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjI1MDM3NTY5fQ.zzwPaF_dSl7yU1mMzC5qPkGAeR6Cx_jJW7IOzo8fyLs"
      },
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "viewBooking",
      id: "2ae328d3-dcee-4365-b8c2-791ea097b3fb",
      method: "GET",
      address: "{{BASE_URL}}/bookings/viewBooking/LEW 7804",
      headers: {
        Authorization:
          "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjI1MDM3NTY5fQ.zzwPaF_dSl7yU1mMzC5qPkGAeR6Cx_jJW7IOzo8fyLs"
      },
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "showAllBookings",
      id: "4e3309c9-a90f-49d2-89dd-daf36cd7acce",
      method: "GET",
      address: "{{BASE_URL}}/bookings/showAllBookings/2/5",
      headers: {
        Authorization:
          "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjI1MDM3NTY5fQ.zzwPaF_dSl7yU1mMzC5qPkGAeR6Cx_jJW7IOzo8fyLs"
      },
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "updateBooking",
      id: "30cc57f5-cff4-4178-bdff-f529ed53e047",
      method: "PUT",
      address: "{{BASE_URL}}/bookings/updateBooking",
      data:
        '{\r\n    "vehicleNumber":"LEW 7804",\r\n    "newBookingDuration":94\r\n}',
      headers: {
        Authorization:
          "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjI1MTIyNzc5fQ.S9jXZesrm7PrIN60uCdcmiDl2RAnaU6UCAkKBSHFSMg"
      },
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "calculateReceipt",
      id: "815ba0a9-950e-4cf9-bd84-84a39f3053e9",
      method: "GET",
      address: "{{BASE_URL}}/bookings/calculateReceipt/LEW 7804",
      headers: {
        Authorization:
          "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjI1MTIyNzc5fQ.S9jXZesrm7PrIN60uCdcmiDl2RAnaU6UCAkKBSHFSMg"
      },
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "calculateFine",
      id: "4cf9b9a2-d51e-469a-89a9-e65ef8f7a782",
      method: "GET",
      address: "{{BASE_URL}}/bookings/calculateFine/LEW 7804",
      headers: {
        Authorization:
          "Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjI1MjA5MTUwfQ.9xHmphBNXmdYF3kdDXmsEkXmMyoxL3TJPnP7LRlSW98"
      },
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });
  });
}
